### ISSUE TITLE
Is there a EasyAr 2.0 version?

### ISSUE THREAD

**Issue by ruidge** [paconcas/EasyAR-JPCT#1]
Is there a EasyAr 2.0 version?

**Comment by paconcas** [comment]
No, sorry!

**Comment by vadhack** [comment]
Hola Pablo (paconcas), podrías guiarme para integrar EasyAR 2.0 y Jpct? por favor, no tengo mucha experiencia con Opengl, cómo easyar puede compartir el mismo glview con jpct?
